import Head from 'next/head'

import { Heading } from '@luiz504-ignite-ui/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ignite Call</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading as={'h1'}>Hello Word</Heading>
      </main>
    </>
  )
}
